config/routes.rb
# coding: utf-8
Rails.application.routes.draw do

  root 'posts#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:index, :show], param: :slug
  resources :authors, only: [:show]

  namespace :admin do
    resources :authors, except: [:index] do
      resources :posts
    end
  end
 
  get 'signup', to: 'admin/authors#new', as: 'signup'
  get 'login',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/account.rb
class Account < ApplicationRecord
  has_secure_password

  belongs_to :author

  validates :email, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_one :account, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :name, presence: true

  validates_associated :account
  accepts_nested_attributes_for :account, update_only: true
end

app/models/post.rb
class Post < ApplicationRecord

  scope :with_author, -> (author_id) { where("author_id = ?", author_id) }
  belongs_to :author
  validates :title, presence: true, uniqueness: true
  validates :summary, presence: true, length: { minimum: 200 }
  before_save :set_slug

  def set_slug()
    self.slug = Slug.new(self.title).value
  end

end

app/models/slug.rb
class Slug

  RULES = [
    {from: /[\s-]/, to: "-"},
    {from: /@/, to: "at"},
    {from: /&/, to: "and"},
    {from: /[\?!\.]/, to: ""}, 
    {from: /\W/, to: "-"},
    {from: /_+|-+/, to: "-"}
  ]

  def initialize(text) 
    @slug = text
  end

  def value
    RULES.reduce(@slug.strip.downcase) do |text, current| 
      text.gsub(current[:from], current[:to])
    end
  end

end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController
  before_action :set_author, only: [:edit, :update, :destroy]
  skip_before_action :authorized, only: [:new, :create]

  def new
    @author = Author.new
    @author.build_account
  end

  def edit
  end

  def create
    if ENV.fetch("RAILS_ENV") == "production"
      redirect_to login_url
    end
    
    @author = Author.create(author_params)

    if @author.save
      session[:account_id] = @author.account.id
      redirect_to admin_author_posts_url(@author)
    else
      render :new
    end
  end

  def update
    if @author.update(author_params)
      redirect_to admin_author_url(@author)
    else
      render :edit
    end
  end

  def destroy
    @author.destroy
    redirect_to new_admin_author_url
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, account_attributes: [:email, :password, :password_confirmation])
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.with_author(current_author.id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_author.posts.create(post_params)

    if @post.save
      redirect_to admin_author_posts_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to admin_author_posts_url current_author
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_author_posts_url current_author
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :summary, :body)
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @account = Account.new
  end

  def create
    @account = Account.find_by_email(params[:email])

    if @account && @account.authenticate(params[:password])
      session[:account_id] = @account.id
      redirect_to admin_author_posts_url(@account.author)
    else
      flash.alert = "Unable to log in. Please check your credentials and try again."
      redirect_to login_url
    end
  end

  def destroy
    session[:account_id] = nil
    redirect_to login_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_account
  helper_method :current_author
  helper_method :logged_in?

  def current_account
    if session[:account_id]
      @current_account ||= Account.find(session[:account_id])
    else
      @current_account = nil
    end
  end

  def current_author
    unless current_account.nil?
      @current_author = current_account.author
    else
      @current_author = nil
    end
  end

  def logged_in?
    !current_account.nil?
  end

  def authorized?
    author_id = params[:author_id]
    author_id ||= params[:id]
    current_author.id == author_id.to_i
  end

  def authorized
    redirect_to "/403" unless authorized?
    redirect_to login_url unless logged_in?
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  skip_before_action :authorized, only: [:show]

  def show
    @author = Author.find(params[:id])
    @posts = Post.with_author(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorized, only: [:index]

  def index
    @posts = Post.order(updated_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authorized, only: [:index, :show]

  def index
    @posts = Post.order(updated_at: :desc)
  end

  def show
    @post = Post.find_by(slug: params[:slug])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized

  def new
    @account = Account.new
  end

  def create
    @account = Account.find_by_email(params[:email])

    if @account && @account.authenticate(params[:password])
      session[:account_id] = @account.id
      redirect_to admin_author_posts_url(@account.author)
    else
      flash.alert = "Unable to log in. Please check your credentials and try again."
      redirect_to login_url
    end
  end

  def destroy
    session[:account_id] = nil
    redirect_to login_url
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link_to(text, path, opts)
    options = current_page?(path) ? { class: "active" } : {}
    content_tag(:li, options) do
      link_to text, path, opts
    end
  end
end

app/helpers/authors_helper.rb
require 'digest'

module AuthorsHelper
  def load_author_avatar(email, size=200)
    hash = Digest::MD5.hexdigest(email.downcase)
    gravatar_url = "https://www.gravatar.com/avatar/"
    image_src = "#{gravatar_url + hash}?s=#{size}"
  end
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def pretty_date(date)
    date.strftime("%d %b, %Y")
  end

  def limit_text(text, max=200, sulfix="...")
    if text.size <= max
      return text
    end

    text.slice(0, max) + sulfix
  end

  def render_markdown(text)
    options = [:hard_wrap, :autolink, :tables, :fenced_code_blocks, :strikethrough]
    Markdown.new(text, *options).to_html.html_safe
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/authors/edit.html.erb
<main class="container">
    <div class="signup">
        <div class="signup__container">
            <p class="signup__title title">Sign up</p>

            <%= form_with(model: @author, url: admin_authors_path, local: true, class: "form") do |author_form| %>

                <%= author_form.text_field :name, class: "field field__text", placeholder: "Name"  %>

                <%= author_form.fields_for :account do |account_form| %>
                    <%= account_form.text_field :email, class: "field field__text", placeholder: "Email" %>
                    <%= account_form.password_field :password, class: "field field__password", placeholder: "Password" %>
                    <%= account_form.password_field :password_confirmation, class: "field field__password", placeholder: "Confirm Password" %>
                <% end %>

                <%= author_form.submit "Create", class: "button button--primary" %>
            <% end %>
        </div>
    </div>
</main>

app/views/admin/authors/new.html.erb
<%= render 'common/messages', entity: @author %>

<main class="container">
    <div class="auth">

        <div class="auth__form">

            <h1 class="auth__title title title--lg">Don't think to much, just write your dreams...</h1>
            <p class="title title--md">Sign up</p>

            <%= form_with(model: @author, url: admin_authors_path, local: true, class: "form") do |author_form| %>
                <div class="field-group">
                    <%= author_form.text_field :name, class: "field field__text", placeholder: "Name"  %>
                </div>

                <%= author_form.fields_for :account do |account_form| %>
                    <div class="field-group">
                        <%= account_form.text_field :email, class: "field field__text", placeholder: "Email" %>
                    </div>
                    <div class="field-group">
                        <%= account_form.password_field :password, class: "field field__password", placeholder: "Password" %>
                    </div>
                    <div class="field-group">
                        <%= account_form.password_field :password_confirmation, class: "field field__password", placeholder: "Confirm Password" %>
                    </div>
                <% end %>

                <%= author_form.submit "Create", class: "button button--block button--primary" %>
            <% end %>
        </div>
        <div class="image">
            <%= image_tag("signup.svg", :alt => "people holding some balloons") %>
        </div>
    </div>
</main>

app/views/admin/posts/_form.html.erb
<%= render 'common/messages', entity: @post %>

<main class="post-form">
    <div class="container">

    <%= form_with(model: [current_author, @post], url: url, local: true, class: "form") do |f| %>
        <div class="post-form__header">
            <div class="field-group post-form__group">
                <%= f.text_field :title, class: "field field__title", placeholder: "Every post begins with a title..."%>
            </div>
        </div>
        <div class="field-group">
            <%= f.text_area :summary, class: "field field__text-area field__text-area--sm", placeholder: "Create a summary is the best way to present your idea..." %>
        </div>
        <div class="tool">
            <ul class="tool__items">
                <li><button class="header-1 tool__button"><%= image_tag("h.svg") %></button></li>
                <li><button class="bold tool__button"><%= image_tag("b.svg") %></button></li>
                <li><button class="italic tool__button"><%= image_tag("i.svg") %></button></li>
                <li><button class="scratch tool__button"><%= image_tag("s.svg") %></button></li>
                <li><span class="tool__separator" /></li>
                <li><button class="ordered-list tool__button"><%= image_tag("ordered.svg") %></button></li>
                <li><button class="unordered-list tool__button"><%= image_tag("unordered.svg") %></button></li>
            </ul>
            <button class="button button--primary">save</button>
        </div>
        <div class="field-group">
            <%= f.text_area :body, class: "editor field field__text-area", placeholder: "Write your body..." %>
        </div>
    <% end %>
    </div>
</main>

<% content_for :head do %>
 <%= javascript_pack_tag 'editor', 'data-turbolinks-track': 'reload' %>
<% end %>

app/views/admin/posts/_item.html.erb
<div class="item">
    <%= link_to post_path(slug: post.slug), class: "item__action", action: 'go' do %>
        <h3 class="item__title"> <%= post.title %></h3>
        <p class="item__body"><%= limit_text(post.summary) %></p>
        <p class="item__date"><%= pretty_date(post.created_at) %></p>
    <% end %>
</div>

app/views/admin/posts/edit.html.erb
<%= render 'form', url: admin_author_post_path %>

app/views/admin/posts/index.html.erb
<main class="posts container">
    <% if !@posts.empty? %>
        <div class="posts__wrapper">
            <div class="posts__left">
                <ul>
                    <% for post in @posts %>
                        <li>
                            <div class="posts__card card">
                                <div class="card__content">
                                    <div class="card__header">
                                        <%= link_to post.title, post_path(slug: post.slug), class: "card__title card__link" %>
                                        <%= image_tag("arrow-right.svg", alt: "a arrow facing to right", class: "card__arrow") %>
                                    </div>
                                    <div class="card__body">
                                        <p class="card__date"><%= pretty_date(post.created_at) %></p>
                                    </div>
                                </div>
                                <div class="card__actions">
                                    <%= link_to "Edit", edit_admin_author_post_path(current_author, post) %>
                                    <%= link_to "Delete", admin_author_post_path(current_author, post), method: :delete %>
                                </div>
                            </div>
                        </li>
                    <% end %>
                </ul>
            </div>
            <div class="posts__right">
                <div class="posts__new-button">
                    <%= link_to "New", new_admin_author_post_path(current_author), class: "button button--secondary" %>
                </div>
                <p class="posts__welcome title title--lg"> Hey <em class="title--em"><%= current_author.name %></em> welcome back, these are yours last posts.</p>
            </div>
        </div>
    <% else %>
        <div class="posts__empty">
            <div class="posts__new-button">
                <%= link_to "New", new_admin_author_post_path(current_author), class: "button button--secondary" %>
            </div>
            <p class="posts__welcome title title--lg"> Hey <em class="title--em"><%= current_author.name %></em> Let's start to write?</p>
        </div>
    <% end %>
</main>

app/views/admin/posts/new.html.erb
<%= render 'form', url: admin_author_posts_path %>

app/views/authors/_form.html.erb
<%= form_with(model: @author, local: true) do |author_form| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% @author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= author_form.label :name %>
      <%= author_form.text_field :name %>
  </div>

  <%= author_form.fields_for :account do |account_form| %>
    <div class="field">
      <%= account_form.label :email %>
      <%= account_form.text_field :email %>
    </div>

    <div class="field">
      <%= account_form.label :password %>
      <%= account_form.password_field :password %>
    </div>

    <div class="field">
      <%= account_form.label :password_confirmation %>
      <%= account_form.password_field :password_confirmation %>
    </div>
  <% end %>

  <div class="actions">
      <%= author_form.submit %>
    </div>
<% end %>

app/views/authors/_profile.html.erb
<%= link_to author_path(author), class: "author__link", action: 'go' do %>
<div class="author__header">
    <div>
        <div class="author__circle">
            <%= image_tag(load_author_avatar(author.account.email), alt: "author image", class: "author__image") %>
        </div>
    </div>
    <div class="author__name">
        <p><%= author.name %></p>
    </div>
</div>    
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |

app/views/authors/show.html.erb
<main class="author">
    <div class="container">
        <%= render 'authors/profile', author: @author %>

        <% if not @posts.empty? %>
            <h1 class="author__title"># Latest posts</h1>
        <% end %>

        <% for post in @posts %>
            <%= render 'admin/posts/item', post: post %>
        <% end %>
    </div>
</main>


<% content_for :title do %> 
    <%= "#{@author.name} |" %> 
<% end %>

<% content_for :head do %>
 <%= tag.meta(name:"description", content: "The latest posts from #{@author.name}!") %>
 <%= tag.meta(name:"author", content: @author.name) %>
<% end %>

app/views/common/_messages.html.erb
<% if entity.errors.full_messages.any? %>
    <% entity.errors.full_messages.each do |error_message| %>
        <div class="message">
            <div class="message__container message--alert">
                <button class="message__button">close</button>
                <p class="message__text"><%= error_message %></p>
            </div>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-167441630-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-167441630-1');
    </script>

    <title><%= yield :title %> Coffee Break</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="google-site-verification" content="N69rReocsNWG0dK5d44vJH2OCffTySAxNT3aGIdENuc" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'messages', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
  </head>

  <body>
      <% if flash.alert %>
          <div class="message">
              <div class="message__container message--alert">
                  <button class="message__button">close</button>
                  <p class="message__text"><%= flash.alert %></p>
              </div>
          </div>
      <% end %>
      <nav class="menu">
          <div class="container menu__container">
              <%= link_to "Coffee Break", root_path, class: "menu__brand" %>
              <% if logged_in?  %>
                  <ul class="navbar">
                      <%= nav_link_to 'Posts', admin_author_posts_path(current_author), class: 'menu__link link' %>
                      <%= nav_link_to 'Profile', author_path(current_author), class: 'menu__link link' %>
                      <%= nav_link_to 'Logout', logout_path, class: 'menu__link link' %>
                  </ul>
              <% else %>
                  <a href="https://github.com/wevnasc/coffee-break" class="button button--primary">Github</a>
              <% end %>
          </div>
      </nav>
      <%= yield %>
      <footer class="footer">
          <div class="container">
              <p class="footer__date">© 2020-<%= Time.current.year %> coffee break</p>
          </div>
      </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<h1>Post</h1>
<%= form_with(model: [current_author, @post], local: true) do |f| %>
    <div class=”field”>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div class=”field”>
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>
    <div class=”actions”>
        <%= f.submit "Save" %>
    </div>
<% end %>

app/views/posts/index.html.erb
<main class="feed">
    <div class="container">
        <div class="hero">
            <h1 class="feed__title title title--lg">Take a seat and enjoy! </h1>
            <p class="feed__title title title--xs">Coffee, tea or water doesn't matter, just have a drink, take a break and read an article!</p>
        </div>
        <% for post in @posts %>
            <%= render 'admin/posts/item', post: post %>
        <% end %>
    </div>
</main>

<% content_for :head do %>
 <%= tag.meta(name:"description", content: "If you like to read good articles about technology, system design, backend development, so this site was made to you. Coffee Break is a site created by a developer with the intention of share acknowledgment, so take a seat and enjoy!") %>
 <%= tag.meta(name:"keywords", content: "coffee break, technology, system design, backend development") %>
<% end %>

app/views/posts/new.html.erb
<h1>Post</h1>
<%= form_with(model: [current_author, @post], local: true) do |f| %>
    <div class=”field”>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div class=”field”>
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>
    <div class=”actions”>
        <%= f.submit "Save" %>
    </div>
<% end %>

app/views/posts/show.html.erb
<main class="post">
    <div class="container">
        <%= render 'authors/profile', author: @post.author %>

        <div class="post__header">
            <h1 class="post__title title--lg"><%= @post.title %></h1>
            <div class="post__information">
                <p class="post__date"><%= pretty_date(@post.created_at) %></p>
            </div>
        </div>

        <article class="article">
            <%= render_markdown(@post.body) %>
        </article>
    </div>
</main>

<% content_for :title do %> 
    <%= "#{@post.title} |" %> 
<% end %>

<% content_for :head do %>
 <%= tag.meta(name:"description", content: limit_text(@post.summary)) %>
 <%= tag.meta(name:"author", content: @post.author.name) %>
<% end %>